SELECT * FROM MOVIES


--Top 10 Highest-Grossing Movies
SELECT TITLE,BOX_OFFICE 
FROM MOVIES 
ORDER BY BOX_OFFICE ASC 
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY

--Average Rating by Year
SELECT TOP 20 RELEASE_YEAR,AVG(RATING) AS AVG_RATING
FROM MOVIES 
GROUP BY RELEASE_YEAR
ORDER BY RELEASE_YEAR 

--Most Popular Genres
SELECT GENRE,COUNT(GENRE) AS TOTAL_GENRE
FROM MOVIES
GROUP BY GENRE
ORDER BY GENRE ASC

--Top Directors by Number of Movies
SELECT DIRECTOR,COUNT(*) AS TOTAL_COUNT
FROM MOVIES
GROUP BY DIRECTOR
ORDER BY TOTAL_COUNT ASC

--Return on Investment (ROI)
SELECT GENRE,BOX_OFFICE,BUDGET,
COUNT(GENRE) AS TOTAL_GENRE,
(BOX_OFFICE-BUDGET) AS ROI
FROM MOVIES
GROUP BY BOX_OFFICE,BUDGET,GENRE
ORDER BY ROI DESC

